# New_2class_Swin_test_multimodal.py
#
# Multimodal（OCT 上 / OCTA3 下，224×448）二元分類 test 評估腳本。
#
# 對應訓練腳本：New_2class_Swin_train_multimodal_oof.py
# 對應建構腳本：New_Build_Multimodal_224x448_Manifest.py
#
# 與 Swin_test_singlemode.py 的差異（共 5 處）：
#   ① INPUT_DIR / CHECKPOINT_ROOT / TEST_EVAL_ROOT 指向 Multimodal_outputs
#   ② 讀取 multimodal_manifest.csv（由 Build 腳本產生）
#   ③ Dataset 讀取 oct0_image_path（224×448 合併影像）
#   ④ Transform resize → (IMG_H, IMG_W) = (448, 224)
#   ⑤ build_model() 傳入 img_size=(IMG_H, IMG_W)，讓 patch_embed 正確處理非正方形
#
# 修正項目（相對前版）：
#   修正①  parse_input_dir() 的 multimodal_out_root：p.parents[5] → p.parents[4]
#           同時加入 training_dir 驗證，提早報錯
#   修正②  CHECKPOINT_ROOT / TEST_EVAL_ROOT 明確寫死到 Multimodal_outputs，
#           不再依賴自動偵測（避免抓到舊 singlemode 路徑）
#   修正③  save_test_preds_csv() 改為接收 df_test，
#           保留 src_oct0_path / src_oct1_path / chosen_oct_type 等追蹤欄位
#
# 執行：
#   python New_2class_Swin_test_multimodal.py
#
# 輸出：
#   TEST_EVAL_ROOT/<model_name>/MULTIMODAL/<run_tag>/Best_fold{N}/
#       confusion_matrix.png
#       roc_curve.png
#       pr_curve.png
#       reliability_diagram.png
#       test_metrics.csv
#       test_summary.json
#       roc_data.csv
#       pr_data.csv
#       calibration_data.csv
#       test_preds.csv            ← 含完整 source tracing 欄位，供 meta-learner / FP-FN 分析
#       test_evaluation_report.txt
#       test_evaluation.log

import gc
import json
import os
import time
import warnings
from pathlib import Path
from typing import Dict, List, Tuple

import matplotlib
matplotlib.use("Agg")
import matplotlib.pyplot as plt
from matplotlib.colors import LinearSegmentedColormap

import numpy as np
import pandas as pd
from scipy.special import expit as _stable_sigmoid
import seaborn as sns

import timm
import torch
import torch.nn as nn
from torch.utils.data import Dataset, DataLoader
from torchvision import transforms
from PIL import Image

from sklearn.metrics import (
    accuracy_score,
    average_precision_score,
    balanced_accuracy_score,
    brier_score_loss,
    confusion_matrix,
    f1_score,
    precision_recall_curve,
    roc_auc_score,
    roc_curve,
)

warnings.filterwarnings("ignore", category=FutureWarning)
warnings.filterwarnings("ignore", category=UserWarning)


# ══════════════════════════════════════════════════════════════════════════════
# ★ CONFIG — Edit only these entries
# ══════════════════════════════════════════════════════════════════════════════

# ★ 1. Best_fold{N} directory produced by New_2class_Swin_train_multimodal_oof.py.
#      Required structure:
#        <MULTIMODAL_OUTPUT_ROOT>/training/<model_name>/MULTIMODAL/<run_tag>/Best_fold{N}
INPUT_DIR = (
    "/data/Irene/SwinTransformer/Swin_Meta/Multimodal_outputs/training/"
    "swin_tiny/MULTIMODAL/"
    "MULTIMODAL_BS16_EP100_LR4e-06_WD0.01_FULL_FINETUNE_FL0.13_0.87_2_WSon_1_2.6/"
    "Best_fold2"   # change to the best fold
)

# ★ 2. multimodal_manifest.csv — generated by New_Build_Multimodal_224x448_Manifest.py.
MULTIMODAL_MANIFEST_CSV = "/data/Irene/Multimodal_224x448/multimodal_manifest.csv"

# ★ 修正②：明確寫死到 Multimodal_outputs，避免誤抓 singlemode checkpoint
CHECKPOINT_ROOT = (
    "/data/Irene/SwinTransformer/Swin_Meta/Multimodal_outputs/checkpoints"
)
TEST_EVAL_ROOT = (
    "/data/Irene/SwinTransformer/Swin_Meta/Multimodal_outputs/test_evaluation"
)

# ── 影像尺寸（與訓練腳本完全一致）────────────────────────────────────────────
IMG_W = 224
IMG_H = 448    # 224×2，OCT 上 / OCTA3 下

# ── Evaluation settings ────────────────────────────────────────────────────────
THRESHOLD   = 0.5
ECE_N_BINS  = 10
BATCH_SIZE  = 16
NUM_WORKERS = 4
RANDOM_SEED = 42

CLASS_NAMES = ["Inactive", "Active"]
MODALITY    = "MULTIMODAL"

# Backbone registry
TIMM_MODEL_MAP: Dict[str, str] = {
    "swin_tiny": "swin_tiny_patch4_window7_224",
}

# multimodal_manifest.csv 中的合併影像路徑欄位（與訓練腳本一致）
MULTIMODAL_IMG_COL = "oct0_image_path"

# ══════════════════════════════════════════════════════════════════════════════
# Plot style constants
# ══════════════════════════════════════════════════════════════════════════════
_TITLE_SIZE      = 15
_AXIS_LABEL_SIZE = 14
_TICK_SIZE       = 12
_LEGEND_SIZE     = 8.5
_ANNOT_SIZE      = 11
_FIG_DPI         = 150

_COL_CALIB_ROC   = "#2563EB"
_COL_CALIB_PR    = "#7C3AED"
_COL_CALIB_REL   = "#2563EB"
_COL_UNCAL       = "#94a3b8"
_COL_RANDOM      = "#374151"
_COL_BASELINE    = "#DC2626"
_COL_PERFECT_CAL = "#374151"
_CM_COLOR_LOW    = "#dbeafe"
_CM_COLOR_HIGH   = "#1e40af"
_CM_ANNOT_SIZE   = 20


# ══════════════════════════════════════════════════════════════════════════════
# Utilities
# ══════════════════════════════════════════════════════════════════════════════

def ensure_dir(p: str) -> None:
    os.makedirs(p, exist_ok=True)


def log(logf, msg: str) -> None:
    line = f"[{time.strftime('%Y-%m-%d %H:%M:%S')}] {msg}"
    print(line)
    if logf:
        logf.write(line + "\n")
        logf.flush()


def sigmoid(x: np.ndarray) -> np.ndarray:
    """Numerically stable sigmoid via scipy.special.expit."""
    return _stable_sigmoid(x).astype(np.float32)


# ══════════════════════════════════════════════════════════════════════════════
# Parse INPUT_DIR
# ══════════════════════════════════════════════════════════════════════════════

def parse_input_dir(input_dir: str) -> dict:
    """
    從 INPUT_DIR 解析所有路徑元件。

    Required structure:
      <MULTIMODAL_OUTPUT_ROOT>/training/<model_name>/MULTIMODAL/<run_tag>/Best_fold{N}

    Path parents mapping（从 leaf 往上數）：
      p              = .../Multimodal_outputs/training/swin_tiny/MULTIMODAL/<run_tag>/Best_foldN
      p.parents[0]   = .../Multimodal_outputs/training/swin_tiny/MULTIMODAL/<run_tag>
      p.parents[1]   = .../Multimodal_outputs/training/swin_tiny/MULTIMODAL
      p.parents[2]   = .../Multimodal_outputs/training/swin_tiny
      p.parents[3]   = .../Multimodal_outputs/training
      p.parents[4]   = .../Multimodal_outputs               ← multimodal_out_root
    """
    p = Path(input_dir).resolve()
    if not p.is_dir():
        raise FileNotFoundError(f"INPUT_DIR not found: {input_dir}")

    leaf = p.name
    if not leaf.startswith("Best_fold"):
        raise ValueError(
            f"INPUT_DIR must end with 'Best_fold{{N}}', got: '{leaf}'"
        )
    try:
        best_fold = int(leaf.replace("Best_fold", ""))
    except ValueError:
        raise ValueError(f"Cannot parse fold number from '{leaf}'.")

    run_tag             = p.parents[0].name   # <run_tag>
    modality_from_path  = p.parents[1].name   # should be "MULTIMODAL"
    model_name          = p.parents[2].name   # e.g. "swin_tiny"
    training_dir        = p.parents[3].name   # should be "training"
    multimodal_out_root = p.parents[4]        # ★ 修正①：p.parents[4] 才是 Multimodal_outputs

    # 路徑結構驗證（提早報錯）
    if training_dir != "training":
        raise ValueError(
            f"INPUT_DIR path structure error: expected parent folder 'training', "
            f"got '{training_dir}'.\n"
            f"Required: <MULTIMODAL_OUTPUT_ROOT>/training/<model>/{MODALITY}/<run_tag>/Best_fold{{N}}"
        )
    if modality_from_path != MODALITY:
        raise ValueError(
            f"Parsed modality from path='{modality_from_path}'，"
            f"但本腳本固定 MODALITY='{MODALITY}'。請確認 INPUT_DIR 路徑結構。"
        )

    return {
        "input_dir":              str(p),
        "model_name":             model_name,
        "modality":               MODALITY,
        "run_tag":                run_tag,
        "best_fold":              best_fold,
        "multimodal_output_root": multimodal_out_root,
    }


# ══════════════════════════════════════════════════════════════════════════════
# Resolve checkpoint path
# ══════════════════════════════════════════════════════════════════════════════

def resolve_checkpoint_path(
    checkpoint_root: str,
    model_name: str,
    run_tag: str,
    best_fold: int,
) -> str:
    """
    訓練腳本儲存路徑：
      Primary  : CHECKPOINT_ROOT/<model>/MULTIMODAL/<run_tag>/Best_fold{N}/model_best.pth
      Fallback : CHECKPOINT_ROOT/<model>/MULTIMODAL/<run_tag>/Kfold/fold{N}/model_best.pth
    """
    base     = os.path.join(checkpoint_root, model_name, MODALITY, run_tag)
    primary  = os.path.join(base, f"Best_fold{best_fold}", "model_best.pth")
    fallback = os.path.join(base, "Kfold", f"fold{best_fold}", "model_best.pth")

    if os.path.isfile(primary):
        return primary
    if os.path.isfile(fallback):
        return fallback

    raise FileNotFoundError(
        f"model_best.pth 找不到。\n"
        f"  Primary  : {primary}\n"
        f"  Fallback : {fallback}\n"
        f"  CHECKPOINT_ROOT = {checkpoint_root}\n\n"
        f"請確認 CHECKPOINT_ROOT 是否正確指向 Multimodal_outputs/checkpoints，"
        f"而非舊的 singlemode checkpoints 目錄。"
    )


# ══════════════════════════════════════════════════════════════════════════════
# Load fold_summary.json
# ══════════════════════════════════════════════════════════════════════════════

def load_fold_summary(input_dir: str, parsed: dict) -> Tuple[float, dict]:
    """
    讀取 INPUT_DIR/fold_summary.json，驗證 fold / modality / model_name 與路徑一致。
    回傳 (temperature, summary_dict)。
    """
    summary_path = os.path.join(input_dir, "fold_summary.json")
    if not os.path.isfile(summary_path):
        raise FileNotFoundError(
            f"fold_summary.json not found: {summary_path}\n"
            "請確認 New_2class_Swin_train_multimodal_oof.py 已完整執行。"
        )
    with open(summary_path, encoding="utf-8") as fh:
        summary = json.load(fh)

    errs = []
    if int(summary["fold"]) != parsed["best_fold"]:
        errs.append(
            f"  fold: path=Best_fold{parsed['best_fold']}, "
            f"JSON fold={summary['fold']}"
        )
    if str(summary.get("modality", "")) != parsed["modality"]:
        errs.append(
            f"  modality: path='{parsed['modality']}', "
            f"JSON='{summary.get('modality')}'"
        )
    if str(summary.get("model_name", "")) != parsed["model_name"]:
        errs.append(
            f"  model_name: path='{parsed['model_name']}', "
            f"JSON='{summary.get('model_name')}'"
        )
    if errs:
        raise ValueError(
            "INPUT_DIR 與 fold_summary.json 不一致：\n" + "\n".join(errs)
        )

    return float(summary["temperature"]), summary


# ══════════════════════════════════════════════════════════════════════════════
# Data loading
# ══════════════════════════════════════════════════════════════════════════════

def normalize_manifest_dtypes(df: pd.DataFrame) -> pd.DataFrame:
    """與訓練腳本的 normalize_manifest_dtypes 完全一致。"""
    out = df.copy()
    for col in ["exam_key", "patient_id", "eye", "exam_date", "split_set"]:
        if col in out.columns:
            out[col] = out[col].astype(str)
    if "y_true" in out.columns:
        out["y_true"] = pd.to_numeric(out["y_true"], errors="coerce")
    for col in ["has_oct0", "has_oct1", "has_octa3", "label_conflict", "fold_id"]:
        if col in out.columns:
            out[col] = pd.to_numeric(out[col], errors="coerce")
    return out


def load_test_dataframe(manifest_csv: str, logf) -> pd.DataFrame:
    """
    讀取 multimodal_manifest.csv，回傳 split_set=='test' 的 rows。

    套用與訓練腳本相同的篩選條件：
      1. label_conflict == 0
      2. y_true not null
      3. oct0_image_path not null / not empty（合併影像路徑）
      4. split_set == 'test'
    """
    required_cols = [
        "exam_key", "patient_id", "split_set", "y_true",
        "label_conflict", "has_oct0", MULTIMODAL_IMG_COL,
    ]

    df = pd.read_csv(manifest_csv)
    df = normalize_manifest_dtypes(df)

    missing = [c for c in required_cols if c not in df.columns]
    if missing:
        raise ValueError(
            f"multimodal_manifest.csv 缺少必要欄位：{missing}\nFile: {manifest_csv}"
        )

    n_raw = len(df)

    df = df[df["label_conflict"] == 0].copy()
    log(logf, f"  After label_conflict==0               : {len(df)} / {n_raw} rows")

    df = df[df["y_true"].notna()].copy()
    log(logf, f"  After y_true notna                    : {len(df)} rows")

    df = df[
        df[MULTIMODAL_IMG_COL].notna() &
        (df[MULTIMODAL_IMG_COL].astype(str).str.strip() != "")
    ].copy()
    log(logf, f"  After {MULTIMODAL_IMG_COL} not-null   : {len(df)} rows")

    for split in ["train_valid", "test"]:
        n = int((df["split_set"] == split).sum())
        log(logf, f"  split_set='{split}' available         : {n} rows")

    df = df[df["split_set"] == "test"].copy().reset_index(drop=True)

    if len(df) == 0:
        raise RuntimeError(
            "篩選後無 test rows。請確認 multimodal_manifest.csv 含 split_set=='test' rows。"
        )

    # 硬性保證：絕對不允許 train_valid row 進入 metric 計算
    assert (df["split_set"] == "train_valid").sum() == 0, \
        "DATA LEAKAGE: train_valid rows found in test DataFrame — abort."

    return df


# ══════════════════════════════════════════════════════════════════════════════
# Model factory
# ══════════════════════════════════════════════════════════════════════════════

def build_model(model_name: str) -> nn.Module:
    """
    建立 num_classes=1 模型（single sigmoid head，output [B,1]）。
    img_size=(IMG_H, IMG_W) = (448, 224) 必須傳入，讓 Swin patch_embed
    正確計算非正方形輸入的 window position embedding。
    """
    if model_name not in TIMM_MODEL_MAP:
        raise NotImplementedError(
            f"model_name='{model_name}' 不在 TIMM_MODEL_MAP。"
            f"已登錄：{list(TIMM_MODEL_MAP.keys())}"
        )
    return timm.create_model(
        TIMM_MODEL_MAP[model_name],
        pretrained=False,
        num_classes=1,
        img_size=(IMG_H, IMG_W),   # ★ (448, 224)，對應訓練時設定
    )


def load_checkpoint(
    model: nn.Module, ckpt_path: str, device: torch.device,
) -> nn.Module:
    """讀取 model_best.pth（訓練腳本儲存格式）。"""
    raw = torch.load(ckpt_path, map_location=device, weights_only=False)
    if isinstance(raw, dict):
        if "model_state_dict" in raw:
            state_dict = raw["model_state_dict"]
        elif "state_dict" in raw:
            state_dict = raw["state_dict"]
        else:
            state_dict = raw
    else:
        state_dict = raw

    model.load_state_dict(state_dict, strict=True)
    model.to(device)
    model.eval()
    return model


# ══════════════════════════════════════════════════════════════════════════════
# Dataset
# ══════════════════════════════════════════════════════════════════════════════

class MultimodalTestDataset(Dataset):
    """
    讀取 multimodal_manifest.csv test rows。
    影像路徑來自 oct0_image_path（224×448 合併影像）。
    任何讀圖失敗直接 raise RuntimeError，不靜默略過。
    """

    def __init__(self, df: pd.DataFrame, transform) -> None:
        self.records   = df[["exam_key", "y_true", MULTIMODAL_IMG_COL]].copy()
        self.transform = transform

    def __len__(self) -> int:
        return len(self.records)

    def __getitem__(self, idx: int):
        row      = self.records.iloc[idx]
        label    = int(row["y_true"])
        exam_key = str(row["exam_key"])
        img_path = str(row[MULTIMODAL_IMG_COL])
        try:
            img = Image.open(img_path).convert("RGB")
        except Exception as e:
            raise RuntimeError(
                f"Failed to read multimodal image: {img_path} "
                f"({type(e).__name__}: {e})"
            )
        if self.transform:
            img = self.transform(img)
        return img, label, exam_key


def get_test_transform() -> transforms.Compose:
    """
    ★ resize 改為 (IMG_H, IMG_W) = (448, 224)，與訓練 tf_val 完全一致。
    無 augmentation。
    """
    return transforms.Compose([
        transforms.Resize((IMG_H, IMG_W)),
        transforms.ToTensor(),
        transforms.Normalize(
            mean=[0.485, 0.456, 0.406],
            std =[0.229, 0.224, 0.225],
        ),
    ])


# ══════════════════════════════════════════════════════════════════════════════
# Inference
# ══════════════════════════════════════════════════════════════════════════════

@torch.no_grad()
def run_inference(
    model: nn.Module,
    loader: DataLoader,
    device: torch.device,
    logf,
) -> Tuple[np.ndarray, np.ndarray, np.ndarray]:
    """
    回傳 (exam_keys, y_true, logits_uncal)。
    model output [B,1] → squeeze(1) → scalar logit [B]。
    """
    all_keys, all_labels, all_logits = [], [], []
    model.eval()
    n_batches = len(loader)

    for i, (imgs, labels, keys) in enumerate(loader):
        imgs        = imgs.to(device)
        out         = model(imgs)                      # [B, 1]
        logits_flat = out.squeeze(1).cpu().numpy()     # [B]

        all_keys.extend(keys)
        all_labels.extend(labels.numpy())
        all_logits.append(logits_flat)

        if (i + 1) % max(1, n_batches // 5) == 0:
            log(logf, f"  Inference: {i+1}/{n_batches} batches done")

    return (
        np.array(all_keys),
        np.array(all_labels, dtype=np.int32),
        np.concatenate(all_logits).astype(np.float32),
    )


# ══════════════════════════════════════════════════════════════════════════════
# Temperature Scaling
# ══════════════════════════════════════════════════════════════════════════════

def apply_temperature_scaling(
    logits: np.ndarray, temperature: float,
) -> Tuple[np.ndarray, np.ndarray]:
    """
    logit_calib = logit / T*
    prob_calib  = sigmoid(logit_calib)

    T* 由訓練腳本在 validation set 上以 LBFGS 最小化 NLL fitting，
    此處直接從 fold_summary.json 載入，不重新 fitting。
    Ref: Guo et al. (2017). On Calibration of Modern Neural Networks. ICML.
    """
    if temperature <= 0:
        raise ValueError(f"Temperature must be > 0, got {temperature}")
    lc = (logits / temperature).astype(np.float32)
    return lc, sigmoid(lc).astype(np.float32)


# ══════════════════════════════════════════════════════════════════════════════
# ECE
# ══════════════════════════════════════════════════════════════════════════════

def compute_ece(
    y_true: np.ndarray, y_prob: np.ndarray, n_bins: int = 10,
) -> Tuple[float, List[dict]]:
    """
    ECE = Σ_b (|B_b|/N) |acc(B_b) − conf(B_b)|  (equal-width bins)

    切割方式：[0, 0.1), [0.1, 0.2), ..., [0.9, 1.0]（最後一個含右端點）。
    空 bin 不計入 ECE，但仍保留在 bins_data（accuracy=None）。
    Ref: Guo et al. (2017), ICML, eq.(3).
    """
    bin_edges = np.linspace(0.0, 1.0, n_bins + 1)
    total_n   = len(y_true)
    ece, bins_data = 0.0, []

    for i in range(n_bins):
        lo, hi = bin_edges[i], bin_edges[i + 1]
        mask   = (y_prob >= lo) & (y_prob < hi)
        if i == n_bins - 1:
            mask |= (y_prob == hi)
        n_bin = int(mask.sum())
        if n_bin == 0:
            bins_data.append({
                "lower": lo, "upper": hi, "n": 0,
                "accuracy": None, "confidence": None,
            })
            continue
        acc  = float(y_true[mask].mean())
        conf = float(y_prob[mask].mean())
        ece += (n_bin / total_n) * abs(acc - conf)
        bins_data.append({
            "lower": lo, "upper": hi, "n": n_bin,
            "accuracy": acc, "confidence": conf,
        })
    return float(ece), bins_data


# ══════════════════════════════════════════════════════════════════════════════
# Metrics
# ══════════════════════════════════════════════════════════════════════════════

def _cls_metrics(
    y_true: np.ndarray, y_pred: np.ndarray,
    y_prob: np.ndarray, prefix: str,
) -> dict:
    """
    完整二元分類 metrics（pos_label=1 即 active）：

    Confusion matrix 定義：
      TP : predicted active,   truly active
      FP : predicted active,   truly inactive
      FN : predicted inactive, truly active
      TN : predicted inactive, truly inactive

    公式：
      Sensitivity (Recall) = TP / (TP + FN)
      Specificity          = TN / (TN + FP)
      PPV (Precision)      = TP / (TP + FP)
      NPV                  = TN / (TN + FN)   ← rule-out safety
      F1 (active)          = 2·PPV·Sens / (PPV+Sens) = 2TP/(2TP+FP+FN)
      Balanced Accuracy    = (Sensitivity + Specificity) / 2
      Brier Score          = mean((prob − y_true)²)
    """
    tn, fp, fn, tp = confusion_matrix(y_true, y_pred, labels=[0, 1]).ravel()
    sens = tp / (tp + fn) if (tp + fn) > 0 else 0.0
    spec = tn / (tn + fp) if (tn + fp) > 0 else 0.0
    ppv  = tp / (tp + fp) if (tp + fp) > 0 else 0.0
    npv  = tn / (tn + fn) if (tn + fn) > 0 else 0.0

    return {
        f"{prefix}_auroc":        float(roc_auc_score(y_true, y_prob)),
        f"{prefix}_auprc":        float(average_precision_score(y_true, y_prob)),
        f"{prefix}_balanced_acc": float(balanced_accuracy_score(y_true, y_pred)),
        f"{prefix}_sensitivity":  float(sens),
        f"{prefix}_specificity":  float(spec),
        f"{prefix}_ppv":          float(ppv),
        f"{prefix}_npv":          float(npv),
        f"{prefix}_f1_active":    float(f1_score(y_true, y_pred,
                                                  pos_label=1, average="binary")),
        f"{prefix}_f1_macro":     float(f1_score(y_true, y_pred, average="macro")),
        f"{prefix}_accuracy":     float(accuracy_score(y_true, y_pred)),
        f"{prefix}_brier":        float(brier_score_loss(y_true, y_prob)),
        f"{prefix}_TP": int(tp), f"{prefix}_FP": int(fp),
        f"{prefix}_FN": int(fn), f"{prefix}_TN": int(tn),
    }


def compute_all_metrics(
    y_true: np.ndarray,
    logits_uncal: np.ndarray,
    temperature: float,
    threshold: float = 0.5,
    ece_n_bins: int  = 10,
) -> Tuple[dict, List[dict], List[dict]]:
    """
    計算 uncalibrated 與 calibrated（post-TS）兩組 metrics。

    流程：
      prob_uncal  = sigmoid(logits_uncal)
      logit_calib = logits_uncal / T*
      prob_calib  = sigmoid(logit_calib)
      y_pred      = (prob >= threshold).astype(int)
    """
    if len(np.unique(y_true)) < 2:
        raise RuntimeError(
            "Test set 只有一個 class，AUROC 無法計算。"
            "請確認 independent test split 包含兩個 class。"
        )

    prob_uncal           = sigmoid(logits_uncal)
    logits_cal, prob_cal = apply_temperature_scaling(logits_uncal, temperature)

    y_pred_uncal = (prob_uncal >= threshold).astype(int)
    y_pred_cal   = (prob_cal   >= threshold).astype(int)

    m_uncal = _cls_metrics(y_true, y_pred_uncal, prob_uncal, "uncal")
    m_calib = _cls_metrics(y_true, y_pred_cal,   prob_cal,   "calib")

    ece_uncal, bins_uncal = compute_ece(y_true, prob_uncal, ece_n_bins)
    ece_calib, bins_calib = compute_ece(y_true, prob_cal,   ece_n_bins)

    n_total    = len(y_true)
    n_active   = int((y_true == 1).sum())
    n_inactive = int((y_true == 0).sum())

    return {
        "n_total":         n_total,
        "n_active":        n_active,
        "n_inactive":      n_inactive,
        "imbalance_ratio": round(n_inactive / n_active, 2) if n_active > 0 else None,
        "threshold":       threshold,
        "temperature":     temperature,
        "ece_n_bins":      ece_n_bins,
        "ece_uncal":       ece_uncal,
        "ece_calib":       ece_calib,
        "ece_reduction":   ece_uncal - ece_calib,   # > 0 表示 TS 改善校準
        **m_uncal,
        **m_calib,
    }, bins_uncal, bins_calib


# ══════════════════════════════════════════════════════════════════════════════
# Plots
# ══════════════════════════════════════════════════════════════════════════════

def _set_style() -> None:
    plt.rcParams.update({
        "font.size":          _ANNOT_SIZE,
        "axes.titlesize":     _TITLE_SIZE,
        "axes.labelsize":     _AXIS_LABEL_SIZE,
        "xtick.labelsize":    _TICK_SIZE,
        "ytick.labelsize":    _TICK_SIZE,
        "figure.dpi":         _FIG_DPI,
        "savefig.dpi":        _FIG_DPI,
        "axes.spines.top":    False,
        "axes.spines.right":  False,
    })


def plot_confusion_matrix(
    y_true: np.ndarray, y_pred: np.ndarray,
    out_path: str, title: str,
) -> None:
    _set_style()
    cm = confusion_matrix(y_true, y_pred, labels=[0, 1])
    fig, ax = plt.subplots(figsize=(5.5, 5))
    cmap = LinearSegmentedColormap.from_list(
        "cm_cmap", [_CM_COLOR_LOW, _CM_COLOR_HIGH]
    )
    sns.heatmap(
        cm, annot=True, fmt="d", cmap=cmap,
        xticklabels=CLASS_NAMES, yticklabels=CLASS_NAMES,
        linewidths=1.0, linecolor="white", ax=ax, cbar=True,
        annot_kws={"size": _CM_ANNOT_SIZE, "weight": "bold"},
    )
    ax.set_xlabel("Predicted label", fontweight="bold")
    ax.set_ylabel("True label",      fontweight="bold")
    plt.tight_layout()
    plt.savefig(out_path, bbox_inches="tight")
    plt.close()


def plot_roc_curve(
    y_true: np.ndarray,
    prob_uncal: np.ndarray, prob_calib: np.ndarray,
    out_path: str, title: str,
) -> Tuple[np.ndarray, np.ndarray, np.ndarray]:
    _set_style()
    auc_u = roc_auc_score(y_true, prob_uncal)
    auc_c = roc_auc_score(y_true, prob_calib)
    fpr_u, tpr_u, _     = roc_curve(y_true, prob_uncal)
    fpr_c, tpr_c, thr_c = roc_curve(y_true, prob_calib)
    fig, ax = plt.subplots(figsize=(5.5, 5))
    ax.plot(fpr_u, tpr_u, color=_COL_UNCAL, lw=1.5, linestyle="--",
            label=f"Uncalibrated  AUC={auc_u:.4f}")
    ax.plot(fpr_c, tpr_c, color=_COL_CALIB_ROC, lw=2,
            label=f"Calibrated (Post-TS)  AUC={auc_c:.4f}")
    ax.plot([0, 1], [0, 1], color=_COL_RANDOM, lw=0.8,
            linestyle="--", alpha=0.5, label="Random")
    ax.set_xlabel("False Positive Rate", fontweight="bold")
    ax.set_ylabel("True Positive Rate",  fontweight="bold")
    ax.legend(loc="lower right", fontsize=_LEGEND_SIZE)
    ax.set_xlim([-0.01, 1.01]); ax.set_ylim([-0.01, 1.01])
    ax.grid(True, alpha=0.25)
    plt.tight_layout()
    plt.savefig(out_path, bbox_inches="tight")
    plt.close()
    return fpr_c, tpr_c, thr_c


def plot_pr_curve(
    y_true: np.ndarray,
    prob_uncal: np.ndarray, prob_calib: np.ndarray,
    out_path: str, title: str,
) -> Tuple[np.ndarray, np.ndarray, np.ndarray]:
    _set_style()
    ap_u     = average_precision_score(y_true, prob_uncal)
    ap_c     = average_precision_score(y_true, prob_calib)
    baseline = float((y_true == 1).mean())
    pre_u, rec_u, _     = precision_recall_curve(y_true, prob_uncal)
    pre_c, rec_c, thr_c = precision_recall_curve(y_true, prob_calib)
    fig, ax = plt.subplots(figsize=(5.5, 5))
    ax.plot(rec_u, pre_u, color=_COL_UNCAL, lw=1.5, linestyle="--",
            label=f"Uncalibrated  AUPRC={ap_u:.4f}")
    ax.plot(rec_c, pre_c, color=_COL_CALIB_PR, lw=2,
            label=f"Calibrated (Post-TS)  AUPRC={ap_c:.4f}")
    ax.axhline(y=baseline, color=_COL_BASELINE, lw=0.8, linestyle=":",
               label=f"Baseline prevalence={baseline:.3f}")
    ax.set_xlabel("Sensitivity", fontweight="bold")
    ax.set_ylabel("Precision",   fontweight="bold")
    ax.legend(loc="upper right", fontsize=_LEGEND_SIZE)
    ax.set_xlim([-0.01, 1.01]); ax.set_ylim([-0.01, 1.05])
    ax.grid(True, alpha=0.25)
    plt.tight_layout()
    plt.savefig(out_path, bbox_inches="tight")
    plt.close()
    return pre_c, rec_c, thr_c


def plot_reliability_diagram(
    bins_uncal: List[dict], bins_calib: List[dict],
    ece_uncal: float, ece_calib: float,
    out_path: str, title: str,
) -> None:
    _set_style()

    def _extract(bins):
        xs, ys, ns = [], [], []
        for b in bins:
            if b["accuracy"] is not None:
                xs.append(b["confidence"])
                ys.append(b["accuracy"])
                ns.append(b["n"])
        return np.array(xs), np.array(ys), np.array(ns)

    xu, yu, nu = _extract(bins_uncal)
    xc, yc, nc = _extract(bins_calib)
    fig, ax = plt.subplots(figsize=(5.5, 5))
    ax.plot([0, 1], [0, 1], color=_COL_PERFECT_CAL, lw=0.8,
            linestyle="--", alpha=0.5, label="Perfect calibration")
    if len(xu) > 0:
        ax.scatter(xu, yu, s=nu / max(nu.max(), 1) * 300 + 30,
                   color=_COL_UNCAL, alpha=0.7, zorder=3,
                   label=f"Uncalibrated  ECE={ece_uncal:.4f}")
        ax.plot(xu, yu, color=_COL_UNCAL, lw=1.2, linestyle="--", alpha=0.6)
    if len(xc) > 0:
        ax.scatter(xc, yc, s=nc / max(nc.max(), 1) * 300 + 30,
                   color=_COL_CALIB_REL, alpha=0.85, zorder=4,
                   label=f"Calibrated (Post-TS)  ECE={ece_calib:.4f}")
        ax.plot(xc, yc, color=_COL_CALIB_REL, lw=1.5)
    ax.set_xlabel("Mean predicted confidence", fontweight="bold")
    ax.set_ylabel("Fraction of positives (accuracy)", fontweight="bold")
    ax.set_title(title, fontweight="bold", pad=10)
    ax.legend(loc="upper left", fontsize=_LEGEND_SIZE)
    ax.set_xlim([-0.02, 1.02]); ax.set_ylim([-0.02, 1.02])
    ax.grid(True, alpha=0.25)
    ax.text(0.98, 0.04,
            f"ECE: {ece_uncal:.4f} → {ece_calib:.4f}\n"
            f"(↓{ece_uncal - ece_calib:.4f})",
            transform=ax.transAxes, ha="right", va="bottom",
            fontsize=_ANNOT_SIZE - 1,
            bbox=dict(boxstyle="round,pad=0.3", facecolor="#f0fdf4",
                      edgecolor="#86efac"))
    plt.tight_layout()
    plt.savefig(out_path, bbox_inches="tight")
    plt.close()


# ══════════════════════════════════════════════════════════════════════════════
# Save output files
# ══════════════════════════════════════════════════════════════════════════════

_METRICS_TABLE = [
    ("AUROC",             "calib_auroc",        "uncal_auroc"),
    ("AUPRC",             "calib_auprc",        "uncal_auprc"),
    ("Balanced_Accuracy", "calib_balanced_acc", "uncal_balanced_acc"),
    ("Sensitivity",       "calib_sensitivity",  "uncal_sensitivity"),
    ("Specificity",       "calib_specificity",  "uncal_specificity"),
    ("PPV",               "calib_ppv",          "uncal_ppv"),
    ("NPV",               "calib_npv",          "uncal_npv"),
    ("F1_active",         "calib_f1_active",    "uncal_f1_active"),
    ("F1_macro",          "calib_f1_macro",     "uncal_f1_macro"),
    ("Accuracy",          "calib_accuracy",     "uncal_accuracy"),
    ("ECE",               "ece_calib",          "ece_uncal"),
    ("Brier_Score",       "calib_brier",        "uncal_brier"),
    ("ECE_reduction",     "ece_reduction",      "ece_reduction"),
]


def save_metrics_csv(metrics: dict, out_path: str) -> None:
    rows = []
    for label, ck, uk in _METRICS_TABLE:
        rows.append({
            "metric":               label,
            "calibrated (post-TS)": round(float(metrics[ck]), 6) if metrics[ck] is not None else None,
            "uncalibrated":         round(float(metrics[uk]), 6) if metrics[uk] is not None else None,
        })
    for label, val in [("temperature", metrics["temperature"]),
                        ("threshold",   metrics["threshold"])]:
        rows.append({"metric": label,
                     "calibrated (post-TS)": val, "uncalibrated": val})
    for col in ("TP", "FP", "FN", "TN"):
        rows.append({
            "metric":               col,
            "calibrated (post-TS)": metrics[f"calib_{col}"],
            "uncalibrated":         metrics[f"uncal_{col}"],
        })
    for col in ("n_total", "n_active", "n_inactive", "imbalance_ratio"):
        rows.append({"metric": col,
                     "calibrated (post-TS)": metrics[col],
                     "uncalibrated":         metrics[col]})
    pd.DataFrame(rows).to_csv(
        out_path, index=False, encoding="utf-8-sig", float_format="%.6f"
    )


def save_test_summary_json(
    metrics: dict, run_cfg: dict, fold_summary: dict, out_path: str,
) -> None:
    import datetime

    def _r(v, ndigits=4):
        return round(float(v), ndigits) if v is not None else None

    summary = {
        "generated_at": datetime.datetime.now().strftime("%Y-%m-%d %H:%M:%S"),

        "run_info": {
            "INPUT_DIR":           run_cfg.get("INPUT_DIR"),
            "model_name":          run_cfg.get("model_name"),
            "timm_backbone":       run_cfg.get("timm_backbone"),
            "modality":            MODALITY,
            "img_size":            f"{IMG_W}x{IMG_H}",
            "run_tag":             run_cfg.get("run_tag"),
            "best_fold":           run_cfg.get("best_fold"),
            "best_epoch":          run_cfg.get("best_epoch"),
            "checkpoint":          run_cfg.get("checkpoint"),
            "multimodal_manifest": run_cfg.get("multimodal_manifest"),
            "out_dir":             run_cfg.get("out_dir"),
            "device":              run_cfg.get("device"),
            "threshold":           run_cfg.get("threshold"),
            "ece_n_bins":          run_cfg.get("ece_n_bins"),
        },

        "training_val_reference": {
            "best_val_bce":  _r(fold_summary.get("best_val_bce"), 6),
            "best_val_auc":  _r(fold_summary.get("best_val_auc"), 4),
            "best_epoch":    fold_summary.get("best_epoch"),
            "val_samples":   fold_summary.get("val_samples"),
            "val_patients":  fold_summary.get("val_patients"),
        },

        "temperature_scaling": {
            "temperature_T*": _r(metrics["temperature"], 6),
            "nll_before_ts":  _r(fold_summary.get("nll_before_ts"), 6),
            "nll_after_ts":   _r(fold_summary.get("nll_after_ts"),  6),
            "ece_uncal":      _r(metrics["ece_uncal"],  4),
            "ece_calib":      _r(metrics["ece_calib"],  4),
            "ece_reduction":  _r(metrics["ece_reduction"], 4),
            "ece_improved":   bool(metrics["ece_reduction"] > 0),
            "note": (
                "T* fitted on validation set only (LBFGS minimising NLL). "
                "Ref: Guo et al. (2017) ICML."
            ),
        },

        "test_dataset": {
            "n_total":         metrics["n_total"],
            "n_active":        metrics["n_active"],
            "n_inactive":      metrics["n_inactive"],
            "imbalance_ratio": metrics["imbalance_ratio"],
            "prevalence":      _r(metrics["n_active"] / metrics["n_total"], 4),
        },

        "calibrated": {
            "AUROC":             _r(metrics["calib_auroc"]),
            "AUPRC":             _r(metrics["calib_auprc"]),
            "Balanced_Accuracy": _r(metrics["calib_balanced_acc"]),
            "Sensitivity":       _r(metrics["calib_sensitivity"]),
            "Specificity":       _r(metrics["calib_specificity"]),
            "PPV":               _r(metrics["calib_ppv"]),
            "NPV":               _r(metrics["calib_npv"]),
            "F1_active":         _r(metrics["calib_f1_active"]),
            "F1_macro":          _r(metrics["calib_f1_macro"]),
            "Accuracy":          _r(metrics["calib_accuracy"]),
            "ECE":               _r(metrics["ece_calib"]),
            "Brier_Score":       _r(metrics["calib_brier"]),
        },

        "uncalibrated": {
            "AUROC":             _r(metrics["uncal_auroc"]),
            "AUPRC":             _r(metrics["uncal_auprc"]),
            "Balanced_Accuracy": _r(metrics["uncal_balanced_acc"]),
            "Sensitivity":       _r(metrics["uncal_sensitivity"]),
            "Specificity":       _r(metrics["uncal_specificity"]),
            "PPV":               _r(metrics["uncal_ppv"]),
            "NPV":               _r(metrics["uncal_npv"]),
            "F1_active":         _r(metrics["uncal_f1_active"]),
            "F1_macro":          _r(metrics["uncal_f1_macro"]),
            "Accuracy":          _r(metrics["uncal_accuracy"]),
            "ECE":               _r(metrics["ece_uncal"]),
            "Brier_Score":       _r(metrics["uncal_brier"]),
        },

        "confusion_matrix_calibrated": {
            "TP": metrics["calib_TP"], "FP": metrics["calib_FP"],
            "FN": metrics["calib_FN"], "TN": metrics["calib_TN"],
            "note": (
                "TP=predicted active & truly active; "
                "FP=predicted active & truly inactive; "
                "FN=predicted inactive & truly active; "
                "TN=predicted inactive & truly inactive."
            ),
        },

        "metric_formulas": {
            "Sensitivity":       "TP / (TP + FN)",
            "Specificity":       "TN / (TN + FP)",
            "PPV":               "TP / (TP + FP)",
            "NPV":               "TN / (TN + FN)",
            "F1_active":         "2·PPV·Sensitivity / (PPV + Sensitivity)",
            "Balanced_Accuracy": "(Sensitivity + Specificity) / 2",
            "Brier_Score":       "mean((prob - y_true)^2)",
            "ECE":               "sum_b (|B_b|/N)|acc(B_b) - conf(B_b)|",
            "AUROC":             "Area Under ROC Curve (threshold-free)",
            "AUPRC":             "Average Precision = sum_k (R_k - R_{k-1}) * P_k",
            "ece_reduction":     "ece_uncal - ece_calib (>0 means TS improved calibration)",
        },

        "references": {
            "Temperature_Scaling": "Guo et al. (2017). On Calibration of Modern Neural Networks. ICML.",
            "AUROC_AUPRC":         "Saito & Rehmsmeier (2015). PLOS ONE.",
            "ECE":                 "Guo et al. (2017). ICML, eq.(3).",
            "NPV_Clinical":        "STARD-AI, Nature Medicine 2020.",
        },
    }

    with open(out_path, "w", encoding="utf-8") as fh:
        json.dump(summary, fh, indent=2, ensure_ascii=False, default=str)


def save_curve_csv(
    col1: np.ndarray, col2: np.ndarray, col3: np.ndarray,
    col_names: List[str], out_path: str,
) -> None:
    n = len(col1)
    if len(col3) == n - 1:
        col3 = np.append(col3, np.nan)
    pd.DataFrame({col_names[0]: col1, col_names[1]: col2,
                  col_names[2]: col3}).to_csv(
        out_path, index=False, encoding="utf-8-sig", float_format="%.6f")


def save_calibration_csv(
    bins_uncal: List[dict], bins_calib: List[dict], out_path: str,
) -> None:
    rows = []
    for bu, bc in zip(bins_uncal, bins_calib):
        rows.append({
            "bin_lower": bu["lower"], "bin_upper": bu["upper"],
            "bin_mid":   (bu["lower"] + bu["upper"]) / 2,
            "n_uncal":    bu["n"],    "acc_uncal":  bu["accuracy"],
            "conf_uncal": bu["confidence"],
            "n_calib":    bc["n"],    "acc_calib":  bc["accuracy"],
            "conf_calib": bc["confidence"],
        })
    pd.DataFrame(rows).to_csv(
        out_path, index=False, encoding="utf-8-sig", float_format="%.6f")


def save_test_preds_csv(
    df_test: pd.DataFrame,
    logits_uncal: np.ndarray,
    temperature: float,
    out_path: str,
) -> None:
    """
    ★ 修正③：接收 df_test，保留 source tracing 欄位。
    供 meta-learner 使用，同時支援 FP/FN 分析與 Grad-CAM 追蹤。

    輸出欄位：
      exam_key, patient_id, eye, exam_date, split_set, fold_id, y_true,
      oct0_image_path（合併影像路徑）,
      src_oct0_path, src_oct1_path, chosen_oct_type（原始 OCT 追蹤）,
      src_oct_path, src_octa3_path（原始來源路徑）,
      logit_uncal, prob_uncal, temperature, logit_calib, prob_calib
    """
    prob_uncal           = sigmoid(logits_uncal)
    logits_cal, prob_cal = apply_temperature_scaling(logits_uncal, temperature)

    out = df_test.copy().reset_index(drop=True)
    out["logit_uncal"] = logits_uncal
    out["prob_uncal"]  = prob_uncal
    out["temperature"] = temperature
    out["logit_calib"] = logits_cal
    out["prob_calib"]  = prob_cal

    keep_cols = [
        # 基本 metadata
        "exam_key", "patient_id", "eye", "exam_date",
        "split_set", "fold_id", "y_true",
        # 合併影像路徑
        MULTIMODAL_IMG_COL,
        # OCT source tracing（來自 Build 腳本）
        "src_oct0_path", "src_oct1_path", "chosen_oct_type",
        "src_oct_path",  "src_octa3_path",
        # 預測結果
        "logit_uncal", "prob_uncal",
        "temperature", "logit_calib", "prob_calib",
    ]
    keep_cols = [c for c in keep_cols if c in out.columns]
    out[keep_cols].to_csv(
        out_path, index=False, encoding="utf-8-sig", float_format="%.6f"
    )


# ══════════════════════════════════════════════════════════════════════════════
# Report & summary logger
# ══════════════════════════════════════════════════════════════════════════════

def log_summary_table(logf, metrics: dict, model_name: str) -> None:
    SEP = "─" * 70
    log(logf, SEP)
    log(logf, f"SUMMARY TABLE  —  {model_name.upper()} / {MODALITY} "
              f"({IMG_W}×{IMG_H})  threshold={metrics['threshold']:.2f}")
    log(logf, SEP)
    log(logf, f"  {'Metric':<22}  {'Uncalib':>10}  {'Calibrated':>12}")
    log(logf, f"  {'─'*22}  {'─'*10}  {'─'*12}")
    for label, key in [
        ("AUROC",             "auroc"),
        ("AUPRC",             "auprc"),
        ("Balanced Accuracy", "balanced_acc"),
        ("Sensitivity",       "sensitivity"),
        ("Specificity",       "specificity"),
        ("PPV",               "ppv"),
        ("NPV",               "npv"),
        ("F1 (active)",       "f1_active"),
        ("F1 (macro)",        "f1_macro"),
        ("Accuracy",          "accuracy"),
        ("Brier Score",       "brier"),
    ]:
        log(logf, f"  {label:<22}  "
                  f"{metrics[f'uncal_{key}']:>10.4f}  "
                  f"{metrics[f'calib_{key}']:>12.4f}")
    log(logf, f"  {'─'*22}  {'─'*10}  {'─'*12}")
    log(logf, f"  {'ECE':<22}  "
              f"{metrics['ece_uncal']:>10.4f}  "
              f"{metrics['ece_calib']:>12.4f}")
    log(logf, SEP)
    log(logf, f"  Confusion Matrix (calib):  "
              f"TP={metrics['calib_TP']}  FP={metrics['calib_FP']}  "
              f"FN={metrics['calib_FN']}  TN={metrics['calib_TN']}")
    log(logf, SEP)


def write_report(metrics: dict, run_cfg: dict, out_path: str) -> None:
    sep  = "=" * 72
    sep2 = "─" * 72
    with open(out_path, "w", encoding="utf-8") as f:
        f.write(f"{sep}\n")
        f.write("MULTIMODAL BASE MODEL — INDEPENDENT TEST SET EVALUATION REPORT\n")
        f.write(f"{sep}\n\n")

        f.write("[RUN CONFIG]\n")
        for k, v in run_cfg.items():
            f.write(f"  {k:<36}: {v}\n")

        n, na, ni = metrics["n_total"], metrics["n_active"], metrics["n_inactive"]
        f.write("\n[TEST SET COMPOSITION]\n")
        f.write(f"  Total    : {n}\n")
        f.write(f"  Active   : {na}  ({na/n*100:.1f}%)\n")
        f.write(f"  Inactive : {ni}  ({ni/n*100:.1f}%)\n")
        _imb = metrics["imbalance_ratio"]
        f.write(f"  Imbalance: {f'{_imb:.2f}:1' if _imb is not None else 'undefined'}\n")

        f.write("\n[TEMPERATURE SCALING]\n")
        f.write(f"  T* (val set)  : {metrics['temperature']:.6f}\n")
        f.write(f"  ECE uncal     : {metrics['ece_uncal']:.4f}\n")
        f.write(f"  ECE calib     : {metrics['ece_calib']:.4f}\n")
        d = "↓ improved" if metrics["ece_reduction"] > 0 else "↑ worsened"
        f.write(f"  ECE Δ         : {metrics['ece_reduction']:.4f}  ({d})\n")
        f.write(f"  Brier uncal   : {metrics['uncal_brier']:.4f}\n")
        f.write(f"  Brier calib   : {metrics['calib_brier']:.4f}\n")

        f.write("\n[METRIC FORMULAS]\n")
        f.write(f"  Sensitivity       = TP / (TP + FN)\n")
        f.write(f"  Specificity       = TN / (TN + FP)\n")
        f.write(f"  PPV               = TP / (TP + FP)\n")
        f.write(f"  NPV               = TN / (TN + FN)\n")
        f.write(f"  F1 (active)       = 2·PPV·Sensitivity / (PPV + Sensitivity)\n")
        f.write(f"  Balanced Accuracy = (Sensitivity + Specificity) / 2\n")
        f.write(f"  Brier Score       = mean((prob - y_true)^2)\n")
        f.write(f"  ECE               = Σ_b (|B_b|/N)|acc(B_b) - conf(B_b)|\n")
        f.write(f"  AUROC             = Area Under ROC Curve (threshold-free)\n")
        f.write(f"  AUPRC             = Σ_k (R_k - R_{{k-1}}) × P_k\n")

        f.write("\n[1. DISCRIMINATIVE PERFORMANCE]\n")
        f.write(f"  {'Metric':<25}  {'Uncalib':>10}  {'Calibrated':>12}\n")
        f.write(f"  {'-'*25}  {'-'*10}  {'-'*12}\n")
        for m in ["auroc", "auprc"]:
            f.write(f"  {m.upper():<25}  "
                    f"{metrics[f'uncal_{m}']:>10.4f}  "
                    f"{metrics[f'calib_{m}']:>12.4f}\n")

        f.write(f"\n[2. THRESHOLD-BASED METRICS  (thr={metrics['threshold']:.2f})]\n")
        f.write(f"  {'Metric':<25}  {'Uncalib':>10}  {'Calibrated':>12}\n")
        f.write(f"  {'-'*25}  {'-'*10}  {'-'*12}\n")
        for m, lbl in [
            ("balanced_acc", "Balanced Accuracy"),
            ("sensitivity",  "Sensitivity"),
            ("specificity",  "Specificity"),
            ("ppv",          "PPV"),
            ("npv",          "NPV"),
            ("f1_active",    "F1 (active)"),
            ("f1_macro",     "F1 (macro)"),
            ("accuracy",     "Accuracy"),
        ]:
            f.write(f"  {lbl:<25}  "
                    f"{metrics[f'uncal_{m}']:>10.4f}  "
                    f"{metrics[f'calib_{m}']:>12.4f}\n")

        f.write("\n[3. CLINICAL SAFETY METRICS  (calibrated)]\n")
        f.write(f"  PPV (active)    : {metrics['calib_ppv']:.4f}\n")
        f.write(f"  NPV (inactive)  : {metrics['calib_npv']:.4f}  ← rule-out safety\n")
        f.write(f"  Balanced Acc    : {metrics['calib_balanced_acc']:.4f}\n")
        f.write("\n  Confusion Matrix (calibrated):\n")
        f.write( "                        Pred active   Pred inactive\n")
        f.write(f"    True active      {metrics['calib_TP']:>12}  "
                f"{metrics['calib_FN']:>14}\n")
        f.write(f"    True inactive    {metrics['calib_FP']:>12}  "
                f"{metrics['calib_TN']:>14}\n")

        f.write("\n[4. CALIBRATION QUALITY]\n")
        f.write(f"  ECE  : {metrics['ece_uncal']:.4f} → {metrics['ece_calib']:.4f}\n")
        f.write(f"  Brier: {metrics['uncal_brier']:.4f} → {metrics['calib_brier']:.4f}\n")

        f.write(f"\n{sep2}\n")
        f.write("SUMMARY TABLE  (calibrated, post-TS)\n")
        f.write(f"{sep2}\n")
        f.write(f"  {'Metric':<22}  {'Value':>10}\n")
        f.write(f"  {'-'*22}  {'-'*10}\n")
        for lbl, key in [
            ("AUROC",             "calib_auroc"),
            ("AUPRC",             "calib_auprc"),
            ("Balanced Accuracy", "calib_balanced_acc"),
            ("Sensitivity",       "calib_sensitivity"),
            ("Specificity",       "calib_specificity"),
            ("PPV",               "calib_ppv"),
            ("NPV",               "calib_npv"),
            ("F1 (active)",       "calib_f1_active"),
            ("F1 (macro)",        "calib_f1_macro"),
            ("Accuracy",          "calib_accuracy"),
            ("ECE",               "ece_calib"),
            ("Brier",             "calib_brier"),
        ]:
            f.write(f"  {lbl:<22}  {metrics[key]:>10.4f}\n")
        f.write(f"{sep2}\n")

        f.write("\n[REFERENCES]\n")
        f.write("  AUROC/AUPRC : Saito & Rehmsmeier, PLOS ONE 2015\n")
        f.write("    https://doi.org/10.1371/journal.pone.0118432\n")
        f.write("  ECE / TS    : Guo et al., ICML 2017\n")
        f.write("    https://proceedings.mlr.press/v70/guo17a.html\n")
        f.write("  NPV Clinical: STARD-AI, Nature Medicine 2020\n")
        f.write("    https://doi.org/10.1038/s41591-020-0941-1\n")

        f.write("\n[OUTPUT FILES]\n")
        for fname in [
            "confusion_matrix.png",
            "roc_curve.png",
            "pr_curve.png",
            "reliability_diagram.png",
            "test_metrics.csv         (tall-format: one row per metric)",
            "test_summary.json        (structured summary with formulas & references)",
            "roc_data.csv",
            "pr_data.csv",
            "calibration_data.csv",
            "test_preds.csv           (KEY: src tracing + predictions, for meta-learner)",
            "test_evaluation_report.txt",
            "test_evaluation.log",
        ]:
            f.write(f"  {fname}\n")


# ══════════════════════════════════════════════════════════════════════════════
# MAIN
# ══════════════════════════════════════════════════════════════════════════════

def main() -> None:
    torch.manual_seed(RANDOM_SEED)
    np.random.seed(RANDOM_SEED)
    device = torch.device("cuda" if torch.cuda.is_available() else "cpu")

    # ── Step 0: Parse INPUT_DIR ───────────────────────────────────────────────
    parsed    = parse_input_dir(INPUT_DIR)
    model_name = parsed["model_name"]
    run_tag    = parsed["run_tag"]
    best_fold  = parsed["best_fold"]

    ckpt_path = resolve_checkpoint_path(CHECKPOINT_ROOT, model_name, run_tag, best_fold)

    out_dir = os.path.join(
        TEST_EVAL_ROOT, model_name, MODALITY, run_tag, f"Best_fold{best_fold}",
    )
    ensure_dir(out_dir)

    temperature, fold_summary = load_fold_summary(INPUT_DIR, parsed)

    logf = open(
        os.path.join(out_dir, "test_evaluation.log"),
        "a", buffering=1, encoding="utf-8"
    )

    print(f"\n{'='*72}")
    print(f"  MULTIMODAL BASE MODEL TEST EVALUATION")
    print(f"  {model_name.upper()} / {MODALITY} ({IMG_W}×{IMG_H}) / fold {best_fold}")
    print(f"  INPUT_DIR: {INPUT_DIR}")
    print(f"{'='*72}")

    log(logf, "=" * 72)
    log(logf, "MULTIMODAL BASE MODEL TEST EVALUATION")
    log(logf, f"  model_name           : {model_name}")
    log(logf, f"  modality             : {MODALITY} ({IMG_W}×{IMG_H}, OCT top / OCTA3 bottom)")
    log(logf, f"  run_tag              : {run_tag}")
    log(logf, f"  best_fold            : {best_fold}")
    log(logf, f"  INPUT_DIR            : {INPUT_DIR}")
    log(logf, f"  multimodal_manifest  : {MULTIMODAL_MANIFEST_CSV}")
    log(logf, f"  checkpoint           : {ckpt_path}")
    log(logf, f"  out_dir              : {out_dir}")
    log(logf, f"  device               : {device}")
    log(logf, f"  timm_model           : {TIMM_MODEL_MAP[model_name]}  img_size=({IMG_H},{IMG_W})")
    log(logf, f"  num_classes          : 1  (single sigmoid head, output [B,1])")
    log(logf, f"  temperature T*       : {temperature:.6f}  (from val set, LBFGS NLL fitting)")
    nll_before = fold_summary.get("nll_before_ts")
    nll_after  = fold_summary.get("nll_after_ts")
    if nll_before is not None:
        log(logf, f"  NLL before TS        : {nll_before:.6f}")
    if nll_after is not None:
        log(logf, f"  NLL after  TS        : {nll_after:.6f}")
    log(logf, f"  best_val_bce         : {fold_summary.get('best_val_bce', 'n/a')}")
    log(logf, f"  best_val_auc         : {fold_summary.get('best_val_auc', 'n/a')}")
    log(logf, f"  best_epoch           : {fold_summary.get('best_epoch', 'n/a')}")

    # ── Step 1: Load test data ────────────────────────────────────────────────
    log(logf, "─" * 72)
    log(logf, "Step 1: Load test split from multimodal_manifest.csv")
    log(logf, f"  Filters: label_conflict==0 → y_true notna → "
              f"{MULTIMODAL_IMG_COL} notna → split_set=='test'")

    df_test  = load_test_dataframe(MULTIMODAL_MANIFEST_CSV, logf)
    n_test   = len(df_test)
    n_active = int((df_test["y_true"] == 1).sum())
    n_inact  = int((df_test["y_true"] == 0).sum())
    _imb_str = f"{n_inact/n_active:.2f}:1" if n_active > 0 else "undefined"
    log(logf, f"  Test set final : {n_test} samples  "
              f"active={n_active} ({n_active/n_test*100:.1f}%)  "
              f"inactive={n_inact} ({n_inact/n_test*100:.1f}%)  "
              f"imbalance={_imb_str}")

    # ── Step 2: Build model and load checkpoint ───────────────────────────────
    log(logf, "─" * 72)
    log(logf, "Step 2: Build model and load checkpoint")

    model = build_model(model_name)

    # dummy forward 確認 448×224 可通過
    model.eval()
    with torch.no_grad():
        dummy     = torch.randn(1, 3, IMG_H, IMG_W)
        dummy_out = model(dummy)
    if dummy_out.shape != (1, 1):
        raise RuntimeError(
            f"Dummy forward shape 不符：{dummy_out.shape}，期望 (1,1)。"
            f"請確認 timm model 支援 img_size=({IMG_H},{IMG_W})。"
        )

    model = load_checkpoint(model, ckpt_path, device)
    log(logf, f"  Model ready: {TIMM_MODEL_MAP[model_name]}  "
              f"img_size=({IMG_H},{IMG_W})  num_classes=1  output=[B,1]")

    # ── Step 3: DataLoader ────────────────────────────────────────────────────
    log(logf, "─" * 72)
    log(logf, "Step 3: Create DataLoader")

    test_ds = MultimodalTestDataset(df_test, get_test_transform())
    test_loader = DataLoader(
        test_ds, batch_size=BATCH_SIZE, shuffle=False,
        num_workers=NUM_WORKERS, pin_memory=(device.type == "cuda"),
    )
    log(logf, f"  DataLoader: {len(test_ds)} samples  "
              f"{len(test_loader)} batches  bs={BATCH_SIZE}")

    # ── Step 4: Inference ─────────────────────────────────────────────────────
    log(logf, "─" * 72)
    log(logf, "Step 4: Inference")

    if device.type == "cuda":
        torch.cuda.synchronize()
    start = time.perf_counter()

    exam_keys, y_true, logits_uncal = run_inference(model, test_loader, device, logf)

    if device.type == "cuda":
        torch.cuda.synchronize()
    elapsed = time.perf_counter() - start

    # ── Safety check: ensure inference order matches df_test metadata ─────────
    # This is important because save_test_preds_csv() appends logits directly
    # to df_test.copy(). If the order is mismatched, predictions would be
    # assigned to the wrong exam/patient.
    expected_keys = df_test["exam_key"].astype(str).to_numpy()
    returned_keys = exam_keys.astype(str)

    if len(returned_keys) != len(expected_keys):
        raise RuntimeError(
            "exam_key length mismatch between DataLoader output and df_test.\n"
            f"  len(returned_keys) = {len(returned_keys)}\n"
            f"  len(expected_keys) = {len(expected_keys)}"
        )

    if not np.array_equal(returned_keys, expected_keys):
        mismatch_idx = np.where(returned_keys != expected_keys)[0]
        examples = []
        for idx in mismatch_idx[:10]:
            examples.append({
                "index": int(idx),
                "returned_exam_key": str(returned_keys[idx]),
                "expected_exam_key": str(expected_keys[idx]),
            })

        raise RuntimeError(
            "exam_key order mismatch between DataLoader output and df_test.\n"
            "Predictions would be assigned to the wrong metadata rows.\n"
            f"Number of mismatches: {len(mismatch_idx)}\n"
            f"First mismatches: {examples}\n"
            "Please check DataLoader shuffle/order and Dataset indexing."
        )

    log(logf, "  exam_key order check passed: DataLoader output matches df_test order.")

    log(logf, f"  Inference done: {len(y_true)} samples  elapsed={elapsed:.2f}s")
    log(logf, f"  logit range [{logits_uncal.min():.3f}, {logits_uncal.max():.3f}]  "
              f"mean={logits_uncal.mean():.3f}")

    # ── Step 5: Temperature Scaling ───────────────────────────────────────────
    log(logf, "─" * 72)
    log(logf, f"Step 5: Temperature Scaling (T*={temperature:.6f})")

    logits_calib, prob_calib = apply_temperature_scaling(logits_uncal, temperature)
    prob_uncal = sigmoid(logits_uncal)

    log(logf, f"  prob_uncal [{prob_uncal.min():.3f}, {prob_uncal.max():.3f}]  "
              f"mean={prob_uncal.mean():.3f}")
    log(logf, f"  prob_calib [{prob_calib.min():.3f}, {prob_calib.max():.3f}]  "
              f"mean={prob_calib.mean():.3f}")

    # ── Step 6: Metrics ───────────────────────────────────────────────────────
    log(logf, "─" * 72)
    log(logf, "Step 6: Compute metrics")

    metrics, bins_uncal, bins_calib = compute_all_metrics(
        y_true, logits_uncal, temperature,
        threshold=THRESHOLD, ece_n_bins=ECE_N_BINS,
    )
    log_summary_table(logf, metrics, model_name)

    # ── Step 7: Plots ─────────────────────────────────────────────────────────
    log(logf, "─" * 72)
    log(logf, "Step 7: Generate plots")

    y_pred_calib = (prob_calib >= THRESHOLD).astype(int)
    title_prefix = f"{model_name.upper()} / {MODALITY} ({IMG_W}×{IMG_H}) / fold {best_fold}"

    plot_confusion_matrix(
        y_true, y_pred_calib,
        os.path.join(out_dir, "confusion_matrix.png"), title_prefix,
    )
    fpr_c, tpr_c, roc_thr_c = plot_roc_curve(
        y_true, prob_uncal, prob_calib,
        os.path.join(out_dir, "roc_curve.png"),
        f"ROC Curve — {title_prefix}",
    )
    pre_c, rec_c, pr_thr_c = plot_pr_curve(
        y_true, prob_uncal, prob_calib,
        os.path.join(out_dir, "pr_curve.png"),
        f"Precision-Recall Curve — {title_prefix}",
    )
    plot_reliability_diagram(
        bins_uncal, bins_calib,
        metrics["ece_uncal"], metrics["ece_calib"],
        os.path.join(out_dir, "reliability_diagram.png"),
        f"Reliability Diagram — {title_prefix}",
    )
    log(logf, "  Plots saved.")

    # ── Step 8: Save data files ───────────────────────────────────────────────
    log(logf, "─" * 72)
    log(logf, "Step 8: Save data files")

    run_cfg = {
        "INPUT_DIR":           INPUT_DIR,
        "model_name":          model_name,
        "timm_backbone":       TIMM_MODEL_MAP[model_name],
        "num_classes":         1,
        "modality":            MODALITY,
        "img_size":            f"{IMG_W}x{IMG_H}",
        "run_tag":             run_tag,
        "best_fold":           best_fold,
        "temperature_T*":      f"{temperature:.6f}",
        "nll_before_ts":       nll_before,
        "nll_after_ts":        nll_after,
        "best_val_bce":        fold_summary.get("best_val_bce"),
        "best_val_auc":        fold_summary.get("best_val_auc"),
        "best_epoch":          fold_summary.get("best_epoch"),
        "checkpoint":          ckpt_path,
        "multimodal_manifest": MULTIMODAL_MANIFEST_CSV,
        "split_set_filter":    "test",
        "threshold":           THRESHOLD,
        "ece_n_bins":          ECE_N_BINS,
        "batch_size":          BATCH_SIZE,
        "img_h":               IMG_H,
        "img_w":               IMG_W,
        "device":              str(device),
        "out_dir":             out_dir,
    }

    save_metrics_csv(metrics, os.path.join(out_dir, "test_metrics.csv"))
    save_curve_csv(fpr_c, tpr_c, roc_thr_c, ["fpr", "tpr", "threshold"],
                   os.path.join(out_dir, "roc_data.csv"))
    save_curve_csv(rec_c, pre_c, pr_thr_c, ["recall", "precision", "threshold"],
                   os.path.join(out_dir, "pr_data.csv"))
    save_calibration_csv(bins_uncal, bins_calib,
                         os.path.join(out_dir, "calibration_data.csv"))

    # ★ 修正③：傳入 df_test，保留 source tracing 欄位
    save_test_preds_csv(
        df_test, logits_uncal, temperature,
        os.path.join(out_dir, "test_preds.csv"),
    )
    save_test_summary_json(metrics, run_cfg, fold_summary,
                           os.path.join(out_dir, "test_summary.json"))
    log(logf, "  All data files saved.")
    log(logf, "  test_preds.csv includes: src_oct0_path / src_oct1_path / "
              "chosen_oct_type / src_octa3_path")

    # ── Step 9: Write text report ─────────────────────────────────────────────
    log(logf, "─" * 72)
    log(logf, "Step 9: Write evaluation report")
    write_report(metrics, run_cfg, os.path.join(out_dir, "test_evaluation_report.txt"))

    # ── Done ──────────────────────────────────────────────────────────────────
    log(logf, "=" * 72)
    log(logf, "EVALUATION COMPLETE")
    log(logf, f"  Results : {out_dir}")
    log(logf, f"  [NEXT]  test_preds.csv → meta-learner evaluation")
    log(logf, "=" * 72)

    logf.close()
    gc.collect()


if __name__ == "__main__":
    main()